### PR TITLE
0.5.3.0

### PR DESCRIPTION
**Pull request by hytonhan**
Necessary changes to to make TimberAPI work with game version 0.5.3

### CODE REVIEW

**Comment by yelvert** [comment]
Working well, been playing it all night, no issues.

**Comment by KYPremco** [comment]
> Working well, been playing it all night, no issues.

Try using the scroll function, with crtl to be specific. Is the only issue left.

**Comment by KYPremco** [comment]
Patch is fine for now, some parts need to be refactored/looked at after update 5 comes live in case more changes will follow.

**Review by KYPremco — COMMENTED** [review]
Oki

**Pull request merged**
